os:
  - Visual Studio 2019
  
platform:
  - x64
  - x86
  
branches:
  only:
    - master

configuration:
  - Release
  
build:
  verbosity: detailed
  
environment:
  projName: $(APPVEYOR_PROJECT_SLUG)
  buildPlatform: $(PLATFORM)
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(PLATFORM)
  
install:
  - cd ..
  - curl -fsS -o pin.zip https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.30-98830-g1d7b601b3-msvc-windows.zip
  - 7z x pin.zip
  - cd pin-3.30-98830-g1d7b601b3-msvc-windows
  - cd source
  - cd tools
  - cp -r ../../../%projName% ./
  - cd %projName%
 
build_script:
  - ps: $PlatformToolset = "v142"
  - ps: (Get-Content PinNSieve.vcxproj) | %{$_ -replace "v110", $PlatformToolset} | Set-Content PinNSieve.vcxproj
  - ps: msbuild PinNSieve.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
  
after_build:
  - dir
  - if [%buildPlatform%]==[x64] ( dir x64\Release\)
  - if [%buildPlatform%]==[x86] ( dir Release\PinNSieve.dll )
  - dir C:\projects\
  - mkdir C:\projects\tiny-tracer\install32_64\%artifactName%
  - if [%buildPlatform%]==[x64] ( cp x64\Release\PinNSieve.dll C:\projects\%projName%\install32_64\%artifactName%\PinNSieve64.dll )
  - if [%buildPlatform%]==[x86] ( cp Release\PinNSieve.dll C:\projects\%projName%\install32_64\%artifactName%\PinNSieve32.dll )
 
artifacts:
  - path: install32_64\%artifactName%
  
